// <auto-generated />
using System;
using LDCWS.DA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LDCWS.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20210202095105_allowedNull")]
    partial class allowedNull
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LDCWS.BO.LoadShedding", b =>
                {
                    b.Property<int>("LoadSheddingSNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("block")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("dataAddedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("dataAddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("hlFeeders")
                        .HasColumnType("int");

                    b.Property<int?>("llFeders")
                        .HasColumnType("int");

                    b.Property<int?>("mlFeeders")
                        .HasColumnType("int");

                    b.Property<DateTime?>("planExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("spell_1_to_and_From")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spell_2_to_and_From")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spell_3_to_and_From")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spell_4_to_and_From")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spell_5_to_and_From")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spell_6_to_and_From")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("totalFeeders")
                        .HasColumnType("int");

                    b.Property<int?>("vhlFeeders")
                        .HasColumnType("int");

                    b.HasKey("LoadSheddingSNO");

                    b.ToTable("loadShedding");
                });

            modelBuilder.Entity("LDCWS.BO.LoadSheddingArchive", b =>
                {
                    b.Property<int>("ArchiveLoadSheddingSNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArchiveAddedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ArchiveAddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoadSheddingSNO")
                        .HasColumnType("int");

                    b.Property<string>("block")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("dataAddedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("dataAddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("hlFeeders")
                        .HasColumnType("int");

                    b.Property<int?>("llFeders")
                        .HasColumnType("int");

                    b.Property<int?>("mlFeeders")
                        .HasColumnType("int");

                    b.Property<DateTime?>("planExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("spell_1_to_and_From")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spell_2_to_and_From")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spell_3_to_and_From")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spell_4_to_and_From")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spell_5_to_and_From")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spell_6_to_and_From")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("totalFeeders")
                        .HasColumnType("int");

                    b.Property<int?>("vhlFeeders")
                        .HasColumnType("int");

                    b.HasKey("ArchiveLoadSheddingSNO");

                    b.ToTable("ArchiveloadShedding");
                });

            modelBuilder.Entity("LDCWS.BO.MasterData", b =>
                {
                    b.Property<int>("MasterDataSNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CAP_MVAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CAP_OK_MVAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Cable_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FEEDER_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FeederID")
                        .HasColumnType("int");

                    b.Property<string>("GridBlock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISLAND")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stage_A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stage_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Switch_Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Switch_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Switch_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Switch_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRAFO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UFR_SW")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dataAddedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("dataAddedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("MasterDataSNO");

                    b.ToTable("MasterData");
                });

            modelBuilder.Entity("LDCWS.BO.MasterDataArchive", b =>
                {
                    b.Property<int>("MasterDataArchiveSNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArchiveAddedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ArchiveAddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CAP_MVAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CAP_OK_MVAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Cable_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FEEDER_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FeederID")
                        .HasColumnType("int");

                    b.Property<string>("GridBlock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISLAND")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MasterDataSNO")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stage_A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stage_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Switch_Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Switch_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Switch_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Switch_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRAFO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UFR_SW")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dataAddedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("dataAddedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("MasterDataArchiveSNO");

                    b.ToTable("ArchiveMasterData");
                });

            modelBuilder.Entity("LDCWS.BO.UserRole", b =>
                {
                    b.Property<int>("userRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("userRoleAddDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("userRoleDesc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userRoleID");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            userRoleID = 1,
                            userRoleAddDateTime = new DateTime(2021, 2, 2, 14, 51, 5, 291, DateTimeKind.Local).AddTicks(8364),
                            userRoleDesc = "System"
                        },
                        new
                        {
                            userRoleID = 2,
                            userRoleAddDateTime = new DateTime(2021, 2, 2, 14, 51, 5, 291, DateTimeKind.Local).AddTicks(9911),
                            userRoleDesc = "Admin"
                        },
                        new
                        {
                            userRoleID = 3,
                            userRoleAddDateTime = new DateTime(2021, 2, 2, 14, 51, 5, 291, DateTimeKind.Local).AddTicks(9954),
                            userRoleDesc = "user"
                        });
                });

            modelBuilder.Entity("LDCWS.BO.Users", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("userAddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("userAddedby")
                        .HasColumnType("int");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userRoleID")
                        .HasColumnType("int");

                    b.HasKey("userID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            userID = 1,
                            userAddedDate = new DateTime(2021, 2, 2, 14, 51, 5, 287, DateTimeKind.Local).AddTicks(3003),
                            userAddedby = 1,
                            userName = "Admin",
                            userPassword = "Admin",
                            userRoleID = 2
                        },
                        new
                        {
                            userID = 2,
                            userAddedDate = new DateTime(2021, 2, 2, 14, 51, 5, 288, DateTimeKind.Local).AddTicks(8031),
                            userAddedby = 1,
                            userName = "user2",
                            userPassword = "user2",
                            userRoleID = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
